- op: replace
  path: /spec/replicas
  value: 3
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: "128Mi"
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: "200m"
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: "512Mi"
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: "1"