apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: phonebill-front-prod

resources:
- ../../base

namespace: prod

commonLabels:
  environment: prod

images:
- name: acrdigitalgarage01.azurecr.io/phonebill/phonebill-front
  newTag: prod

patches:
- path: deployment-prod.yaml
  target:
    kind: Deployment
    name: phonebill-front

configMapGenerator:
- name: phonebill-front-config
  env: config.env