apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-phonebill-front
data:
  runtime-env.js: |
    // 런타임 환경 설정 - PRODUCTION
    window.__runtime_config__ = {
      // API 서버 설정 (운영환경)
      USER_HOST: 'https://phonebill-api.domain.com',
      BILL_HOST: 'https://phonebill-api.domain.com', 
      PRODUCT_HOST: 'https://phonebill-api.domain.com',
      KOS_MOCK_HOST: 'https://phonebill-api.domain.com',
      API_GROUP: '/api/v1',
      
      // 환경 설정
      NODE_ENV: 'production',
      
      // 기타 설정
      APP_NAME: '통신요금 관리 서비스',
      VERSION: '1.0.0'
    };