apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-phonebill-front
data:
  runtime-env.js: |
    // 런타임 환경 설정 - STAGING
    window.__runtime_config__ = {
      // API 서버 설정 (스테이징환경)
      USER_HOST: 'https://phonebill-api-staging.domain.com',
      BILL_HOST: 'https://phonebill-api-staging.domain.com', 
      PRODUCT_HOST: 'https://phonebill-api-staging.domain.com',
      KOS_MOCK_HOST: 'https://phonebill-api-staging.domain.com',
      API_GROUP: '/api/v1',
      
      // 환경 설정
      NODE_ENV: 'staging',
      
      // 기타 설정
      APP_NAME: '통신요금 관리 서비스 (스테이징)',
      VERSION: '1.0.0-staging'
    };