apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebill-front
  labels:
    app: phonebill-front
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phonebill-front
  template:
    metadata:
      labels:
        app: phonebill-front
        version: v1
    spec:
      containers:
      - name: phonebill-front
        image: acrdigitalgarage01.azurecr.io/phonebill/phonebill-front:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5