apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: phonebill-front-base

resources:
- deployment.yaml
- service.yaml

commonLabels:
  system: phonebill
  component: frontend
  
images:
- name: acrdigitalgarage01.azurecr.io/phonebill/phonebill-front
  newTag: latest