- op: replace
  path: /spec/replicas
  value: 1
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: "32Mi"
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: "50m"
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: "128Mi"
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: "200m"